workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Clean + recreate Android (v2 embedding) WITHOUT touching lib/
        script: |
          rm -rf android
          flutter create --platforms=android .
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
