workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Flutter doctor
        script: |
          flutter doctor -v

      - name: Create missing platform files
        script: |
          flutter create .

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
