workflows:
  android-apk:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Recreate Android platform
        script: |
          rm -rf android
          flutter create .

      - name: Ensure google-services.json
        script: |
          mkdir -p android/app
          if [ -f google-services.json ]; then
            cp google-services.json android/app/google-services.json
          fi

      - name: Get dependencies
        script: |
          flutter pub get

      - name: Build debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

